# Ödev-20

In [48]:
# ../preprocessing/healthcare_insurance_to_preprocessed.csv 
# veri setini veri ön hazırlığını yapınız.

In [49]:
import pandas as pd

In [50]:
df = pd.read_csv("https://raw.githubusercontent.com/erkansirin78/datasets/master/preprocessing/healthcare_insurance_to_preprocessed.csv")

In [51]:
# Veri seti hakkında detaylı bilgi: 
# https://www.rdocumentation.org/packages/arules/versions/1.6-3/topics/Adult
df.head()

age     sex     bmi  children smoker     region      charges
0  19.0  female     NaN         0    yes  southwest  16884.92400
1  18.0    male  33.770         1     no  southeast   1725.55230
2  28.0    male  33.000         3     no  southeast   4449.46200
3  33.0    male  22.705         0     no  northwest  21984.47061
4  32.0    male  28.880         0     no  northwest   3866.85520

# Kategorik Niteliklerde Boşluk Temizliği (trim - strip())

In [52]:
for i in df.columns:
    if df[i].dtype == object:
        print(i)
        df[i] = df[i].apply(lambda x: x.strip())

sex
smoker
region


# Veri Keşfi 

In [53]:
df.describe()

age          bmi     children       charges
count  1330.000000  1329.000000  1338.000000   1338.000000
mean     39.206767    30.672028     1.094918  13270.422265
std      14.047060     6.103187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.315000     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.700000     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

# Null kontrolü

In [54]:
df.isnull().values.any()

True

In [56]:
df.isnull().sum()

age         8
sex         0
bmi         9
children    0
smoker      0
region      0
charges     0
dtype: int64

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
age         1330 non-null float64
sex         1338 non-null object
bmi         1329 non-null float64
children    1338 non-null int64
smoker      1338 non-null object
region      1338 non-null object
charges     1338 non-null float64
dtypes: float64(3), int64(1), object(3)
memory usage: 73.2+ KB


In [10]:
# bmi niteliğinde boşluklar var.

# Nümerik Değerler içindeki boşlukların doldurulması

### Ortalama veya medyan ile

In [57]:
from sklearn.impute import SimpleImputer

### bmi

In [58]:
imputer_bmi = SimpleImputer(strategy='mean')

In [59]:
df['bmi2'] = imputer_bmi.fit_transform(df['bmi'].values.reshape(-1,1))

In [60]:
df.head(10)

age     sex     bmi  children smoker     region      charges       bmi2
0  19.0  female     NaN         0    yes  southwest  16884.92400  30.672028
1  18.0    male  33.770         1     no  southeast   1725.55230  33.770000
2  28.0    male  33.000         3     no  southeast   4449.46200  33.000000
3  33.0    male  22.705         0     no  northwest  21984.47061  22.705000
4  32.0    male  28.880         0     no  northwest   3866.85520  28.880000
5  31.0  female  25.740         0     no  southeast   3756.62160  25.740000
6  46.0  female  33.440         1     no  southeast   8240.58960  33.440000
7  37.0  female  27.740         3     no  northwest   7281.50560  27.740000
8  37.0    male  29.830         2     no  northeast   6406.41070  29.830000
9  60.0  female  25.840         0     no  northwest  28923.13692  25.840000

## Sabit değerler ile

In [16]:
# bmi hesaplamasını ortalamaya göre değil belkide cinsiyetlere göre yapmak daha uygun olur.
# Boşluk hangi cinsiyete ait ise ona göre bir sabit verilir.

# Temizlik sonuçlarını diske yazılması

In [17]:
df.to_csv("D:/Datasets/preprocessing/healthcare_insurance_ilk_safha.csv", 
          index=False, header=True, sep=",")

# İkinci safha

In [61]:
import pandas as pd
df = pd.read_csv("D:/Datasets/preprocessing/healthcare_insurance_ilk_safha.csv")
df.head()

age     sex     bmi  children smoker     region      charges       bmi2
0  19.0  female     NaN         0    yes  southwest  16884.92400  30.672028
1  18.0    male  33.770         1     no  southeast   1725.55230  33.770000
2  28.0    male  33.000         3     no  southeast   4449.46200  33.000000
3  33.0    male  22.705         0     no  northwest  21984.47061  22.705000
4  32.0    male  28.880         0     no  northwest   3866.85520  28.880000

## Hedef Değişkenin LabelEncoder ile Kodlanması

In [19]:
# Bu veri setinde hedef değişken olmadığından yapılamıyor.

## LabelEncoder

In [25]:
from sklearn.preprocessing import LabelEncoder

In [62]:
lbl_encoder_sex = LabelEncoder()
df['sex2'] = lbl_encoder_sex.fit_transform(df['sex'].values.reshape(-1,1))
df.head()

c:\python\python36\lib\site-packages\sklearn\preprocessing\label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


age     sex     bmi  children smoker     region      charges       bmi2  \
0  19.0  female     NaN         0    yes  southwest  16884.92400  30.672028   
1  18.0    male  33.770         1     no  southeast   1725.55230  33.770000   
2  28.0    male  33.000         3     no  southeast   4449.46200  33.000000   
3  33.0    male  22.705         0     no  northwest  21984.47061  22.705000   
4  32.0    male  28.880         0     no  northwest   3866.85520  28.880000   

   sex2  
0     0  
1     1  
2     1  
3     1  
4     1

In [63]:
lbl_encoder_smoker = LabelEncoder()
df['smoker2'] = lbl_encoder_smoker.fit_transform(df['smoker'].values.reshape(-1,1))
df.head()

age     sex     bmi  children smoker     region      charges       bmi2  \
0  19.0  female     NaN         0    yes  southwest  16884.92400  30.672028   
1  18.0    male  33.770         1     no  southeast   1725.55230  33.770000   
2  28.0    male  33.000         3     no  southeast   4449.46200  33.000000   
3  33.0    male  22.705         0     no  northwest  21984.47061  22.705000   
4  32.0    male  28.880         0     no  northwest   3866.85520  28.880000   

   sex2  smoker2  
0     0        1  
1     1        0  
2     1        0  
3     1        0  
4     1        0

In [64]:
lbl_encoder_region = LabelEncoder()
df['region2'] = lbl_encoder_region.fit_transform(df['region'].values.reshape(-1,1))
df.head()

age     sex     bmi  children smoker     region      charges       bmi2  \
0  19.0  female     NaN         0    yes  southwest  16884.92400  30.672028   
1  18.0    male  33.770         1     no  southeast   1725.55230  33.770000   
2  28.0    male  33.000         3     no  southeast   4449.46200  33.000000   
3  33.0    male  22.705         0     no  northwest  21984.47061  22.705000   
4  32.0    male  28.880         0     no  northwest   3866.85520  28.880000   

   sex2  smoker2  region2  
0     0        1        3  
1     1        0        2  
2     1        0        2  
3     1        0        1  
4     1        0        1

## Sütunları tekrar sıralayalım

In [65]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges', 'bmi2',
       'sex2', 'smoker2', 'region2'],
      dtype='object')

In [66]:
df = df[['bmi2','sex2', 'smoker2', 'region2', 'age', 'charges', 'children',
          'bmi','sex', 'smoker', 'region' ]]

In [67]:
df.head()

bmi2  sex2  smoker2  region2   age      charges  children     bmi  \
0  30.672028     0        1        3  19.0  16884.92400         0     NaN   
1  33.770000     1        0        2  18.0   1725.55230         1  33.770   
2  33.000000     1        0        2  28.0   4449.46200         3  33.000   
3  22.705000     1        0        1  33.0  21984.47061         0  22.705   
4  28.880000     1        0        1  32.0   3866.85520         0  28.880   

      sex smoker     region  
0  female    yes  southwest  
1    male     no  southeast  
2    male     no  southeast  
3    male     no  northwest  
4    male     no  northwest

## OneHotEncoder

In [76]:
X = df.iloc[:,:7].values
X.shape

(1338, 7)

In [77]:
X[:10,:]

array([[3.06720278e+01, 0.00000000e+00, 1.00000000e+00, 3.00000000e+00,
        1.90000000e+01, 1.68849240e+04, 0.00000000e+00],
       [3.37700000e+01, 1.00000000e+00, 0.00000000e+00, 2.00000000e+00,
        1.80000000e+01, 1.72555230e+03, 1.00000000e+00],
       [3.30000000e+01, 1.00000000e+00, 0.00000000e+00, 2.00000000e+00,
        2.80000000e+01, 4.44946200e+03, 3.00000000e+00],
       [2.27050000e+01, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        3.30000000e+01, 2.19844706e+04, 0.00000000e+00],
       [2.88800000e+01, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        3.20000000e+01, 3.86685520e+03, 0.00000000e+00],
       [2.57400000e+01, 0.00000000e+00, 0.00000000e+00, 2.00000000e+00,
        3.10000000e+01, 3.75662160e+03, 0.00000000e+00],
       [3.34400000e+01, 0.00000000e+00, 0.00000000e+00, 2.00000000e+00,
        4.60000000e+01, 8.24058960e+03, 1.00000000e+00],
       [2.77400000e+01, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        3.70000000e+01, 7

In [78]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(handle_unknown='ignore', categories='auto')

In [79]:
# Birden sütunu ilgilendiren dönüşümleri kolay yapabilmek için kullanışlı bir sınıf (Estimator kökenli)
# Biz burada sadece OneHotEncoder için kullanacağız.
from sklearn.compose import ColumnTransformer

In [80]:
# one_hot_encode_with_ct bizim kendi verdiğiiz isimdir. onehotencoder'ı yukarıda yarattık. [2,3] ise dönüşecek
# niteliklerin indeks değerleridir.
ct = ColumnTransformer(
    [('one_hot_encode_with_ct', onehotencoder, [1,2,3]),], 
    remainder='passthrough'
)

In [81]:
# ColumnTransformer nesnesi ile onehotencoder nesnesini eğitip gerekli dönüşümleri gerçekleştirip X'e tekrar atayalım.
# Burada X'in boyutu(shape) değişecektir.
X = ct.fit_transform(X)

In [82]:
X.shape

(1338, 12)

In [83]:
X[:3]

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        3.06720278e+01, 1.90000000e+01, 1.68849240e+04, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        3.37700000e+01, 1.80000000e+01, 1.72555230e+03, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        3.30000000e+01, 2.80000000e+01, 4.44946200e+03, 3.00000000e+00]])

# Normalizasyon, Standardizasyon (StandartdScaler)

In [84]:
from sklearn.preprocessing import StandardScaler

In [85]:
scaler = StandardScaler()

In [86]:
X = scaler.fit_transform()

In [87]:
X[:4,:]

array([[ 1.01051870e+00, -1.01051870e+00, -1.97058663e+00,
         1.97058663e+00, -5.65266864e-01, -5.66417885e-01,
        -6.11323672e-01,  1.76548098e+00,  1.75288657e-15,
        -1.43904616e+00,  2.98583802e-01, -9.08613667e-01],
       [-9.89590795e-01,  9.89590795e-01,  5.07463099e-01,
        -5.07463099e-01, -5.65266864e-01, -5.66417885e-01,
         1.63579466e+00, -5.66417885e-01,  5.09506656e-01,
        -1.51026221e+00, -9.53689174e-01, -7.87671916e-02],
       [-9.89590795e-01,  9.89590795e-01,  5.07463099e-01,
        -5.07463099e-01, -5.65266864e-01, -5.66417885e-01,
         1.63579466e+00, -5.66417885e-01,  3.82868938e-01,
        -7.98101694e-01, -7.28674670e-01,  1.58092576e+00],
       [-9.89590795e-01,  9.89590795e-01,  5.07463099e-01,
        -5.07463099e-01, -5.65266864e-01,  1.76548098e+00,
        -6.11323672e-01, -5.66417885e-01, -1.31029380e+00,
        -4.42021435e-01,  7.19842977e-01, -9.08613667e-01]])