In [ ]:
# Tensorflow, nümerik operasyonlar için güçlü bir açık kaynak kütüphanesidir.


In [1]:
import tensorflow as tf
import numpy as np

# 1. Sabit tanımlama (define a constant)

In [2]:
tensor_20 = tf.constant([[23, 4], [32, 51]])

In [3]:
tensor_20

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]])>

In [4]:
tensor_20.shape

TensorShape([2, 2])

## 1.1. Sabitin değerlerine ulaşma

In [5]:
# session gerektirmeden numpy ile değerlere doğrudan ulaşmak
tensor_20.numpy()

array([[23,  4],
       [32, 51]])

In [6]:
# bu numpy array tekrar Tensorflow'a çevrilebilir
numpy_tensor = np.array([[23, 4], [32, 51]])

In [7]:
tensor_from_numpy = tf.constant(numpy_tensor)
tensor_from_numpy

<tf.Tensor: id=3, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]])>

# 2. Değişkenler (variables)

In [8]:
tf2_variable = tf.Variable(3)

In [9]:
tensor = tf.constant([[1, 2], [3, 4]])

In [10]:
tensor

<tf.Tensor: id=13, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [11]:
tensor + 2

<tf.Tensor: id=16, shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]])>

In [12]:
tensor * 5

<tf.Tensor: id=19, shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]])>

In [13]:
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [14]:
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

# 3. Computation Graph Oluşturma

In [15]:
x = tf.Variable(3, name="x")
y = tf.Variable(4, name="y")

In [16]:
type(x)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [25]:
def my_f(x,y):
    return x*x*y + y + 2

In [26]:
type(my_f)

function

In [27]:
out_a = my_f(x,y)

In [29]:
type(out_a)

tensorflow.python.framework.ops.EagerTensor

In [28]:
print(out_a)

tf.Tensor(42, shape=(), dtype=int32)
