# Veri seti: https://www.kaggle.com/zalando-research/fashionmnist


### Labels
Each training and test example is assigned to one of the following labels:
0. T-shirt/top
1. Trouser
2. Pullover
3. Dress
4. Coat
5. Sandal
6. Shirt
7. Sneaker
8. Bag
9. Ankle boot 

60.000 eğitim, 10.000 test verisi. Her bir resim 28X28 = 784 piksel. 
Her bir piksel 0-255 arasında değer alıyor.

Problem: Resimlerin yukarıdaki giysi türlerinden hangisine ait olduğunu tahmin etmek.

# 1. Kütüphane ve veri

In [1]:
import numpy as np
import datetime
import tensorflow as tf
from tensorflow.keras.datasets import fashion_mnist

In [2]:
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

In [3]:
type(X_train)

numpy.ndarray

# 2. Veri Ön Hazırlığı

In [4]:
# İlk 2 satır. Her bir satır bir resim ve 28x28 bir matris
X_train[100:102]

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]], dtype=uint8)

In [5]:
# Her bir satır bir rakam ve bu rakamlar giysi türlerini gösteriyor: 
# 8. Bag, 0. T-shirt/top
y_train[100:102]

array([8, 0], dtype=uint8)

In [6]:
print("X_train: ", X_train.shape)
print("y_train: ", y_train.shape)
print("X_test: ", X_test.shape)
print("y_test: ", y_test.shape)

X_train:  (60000, 28, 28)
y_train:  (60000,)
X_test:  (10000, 28, 28)
y_test:  (10000,)


## 2.1. Normalizasyon

In [7]:
# 0-255 arası değer alan her bir pikseli 0-1 arasına çekiyoruz.

In [8]:
X_train = X_train / 255
X_test = X_test / 255

## 2.2. Reshape

In [9]:
# Her bir resim bir matris ile temsil ediliyordu. 
# Biz bunu vektör haline getirerek düzleştireceğiz.

In [10]:
X_train = X_train.reshape(-1, 784)

In [11]:
X_train.shape

(60000, 784)

In [12]:
X_train[100:102]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [13]:
X_test = X_test.reshape(-1, 784)
X_test.shape

(10000, 784)

# 3. Yapay Sinir Ağı Örmek 
# (Building an Artificial Neural Network)

## 3.1. Model

In [14]:
# Fully connected ANN
model = tf.keras.models.Sequential()

## 3.2. Fully connected hidden layer

In [15]:
# Katman hiperparametreleri
# sinir hücresi sayısı: 128
# aktivasyon fonksiyon türü: ReLU
# girdi katmanın şekli: (784,)

In [16]:
model.add(tf.keras.layers.Dense(units=128, activation='relu', input_shape=(784,)))

## 3.3. İkinci katmana Dropout Ekleme

In [17]:
# Ragularization technique. Birkatmandaki hücreleri rastsal olarak 0'a ayarlar.
# Böylece bu hücreler geri salınım esnasında güncellenmez, aşırı öğrenmenin önüne geçilmiş olur.

In [18]:
# model.add(tf.keras.layers.Dropout(0.2))

## 3.4. Çıktı Katmanı Ekleme

In [19]:
# units=10 çünkü 10 farklı kategori var
model.add(tf.keras.layers.Dense(units=10, activation='softmax'))

## 3.5. Ağı Derleme (Compiling the model)

In [20]:
# Optimizer ve loss seçilir
# adam: en iyi stochastic gradient descent kullanarak ağırlıkları günceller
# stochastic gradient descent optimize edicileri arasında en iyilerinden

In [21]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy',
             metrics=['sparse_categorical_accuracy'])

In [22]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [23]:
model.fit(X_train, y_train, epochs=5)

Epoch 1/5
60000/60000 [==============================] - 2s 37us/sample - loss: 0.5042 - sparse_categorical_accuracy: 0.8239
Epoch 2/5
60000/60000 [==============================] - 2s 33us/sample - loss: 0.3781 - sparse_categorical_accuracy: 0.86291s - loss: 0.3864 - sparse_categoric
Epoch 3/5
60000/60000 [==============================] - 2s 32us/sample - loss: 0.3397 - sparse_categorical_accuracy: 0.8771
Epoch 4/5
60000/60000 [==============================] - 2s 32us/sample - loss: 0.3138 - sparse_categorical_accuracy: 0.8850
Epoch 5/5
60000/60000 [==============================] - 2s 32us/sample - loss: 0.2958 - sparse_categorical_accuracy: 0.8909


## 3.6. Modeli Değerlendirme

In [24]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)

10000/10000 [==============================] - 0s 23us/sample - loss: 0.3421 - sparse_categorical_accuracy: 0.8762


In [25]:
print("test_loss", test_loss)
print("test_accuracy", test_accuracy)

test_loss 0.3420739956974983
test_accuracy 0.8762
