In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("D:/Datasets/preprocessing/simple_data_ilk_safha.csv")

In [3]:
df.head()

sirano   isim   yas       meslek     sehir  aylik_gelir  yas2  \
0       1  Cemal  35.0         Isci    Ankara       3500.0  35.0   
1       2  Ceyda  42.0        Memur   Kayseri       4200.0  42.0   
2       3  Timur  30.0     Müzisyen  Istanbul       9000.0  30.0   
3       4  Burcu  29.0  Pazarlamaci    Ankara       4200.0  29.0   
4       6    Ali  33.0        Memur    Ankara       4250.0  33.0   

   aylik_gelir2  aylik_gelir3  
0        3500.0        3500.0  
1        4200.0        4200.0  
2        9000.0        9000.0  
3        4200.0        4200.0  
4        4250.0        4250.0

## numpy reshape'i yeniden hatırlayalım

In [4]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
arr.shape

(4,)

In [7]:
arr = arr.reshape(-1,1)
arr

array([[1],
       [2],
       [3],
       [4]])

In [8]:
arr.shape

(4, 1)

In [9]:
df.columns

Index(['sirano', 'isim', 'yas', 'meslek', 'sehir', 'aylik_gelir', 'yas2',
       'aylik_gelir2', 'aylik_gelir3'],
      dtype='object')

## Sütunları tekrar sıralayalım

In [9]:
df.columns

Index(['sirano', 'isim', 'yas', 'meslek', 'sehir', 'aylik_gelir', 'yas2',
       'aylik_gelir2', 'aylik_gelir3'],
      dtype='object')

In [10]:
df = df[['sirano', 'isim', 'yas','aylik_gelir','aylik_gelir2', 'meslek', 'sehir',  'yas2',
        'aylik_gelir3']]

In [11]:
df.head()

sirano   isim   yas  aylik_gelir  aylik_gelir2       meslek     sehir  \
0       1  Cemal  35.0       3500.0        3500.0         Isci    Ankara   
1       2  Ceyda  42.0       4200.0        4200.0        Memur   Kayseri   
2       3  Timur  30.0       9000.0        9000.0     Müzisyen  Istanbul   
3       4  Burcu  29.0       4200.0        4200.0  Pazarlamaci    Ankara   
4       6    Ali  33.0       4250.0        4250.0        Memur    Ankara   

   yas2  aylik_gelir3  
0  35.0        3500.0  
1  42.0        4200.0  
2  30.0        9000.0  
3  29.0        4200.0  
4  33.0        4250.0

# Nitelikler Matrisi oluşturma (Feature matrix)

In [12]:
# tüm satırları ve 5. sütundan (meslek) sona kadar seçelim
X = df.iloc[:,5:].values

In [13]:
# İlk üç satırı görelim
X[:3]

array([['Isci', 'Ankara', 35.0, 3500.0],
       ['Memur', 'Kayseri', 42.0, 4200.0],
       ['Müzisyen', 'Istanbul', 30.0, 9000.0]], dtype=object)

In [14]:
X.shape

(14, 4)

In [15]:
# Mesleklerin bulunduğu sütunu nasıl seçeriz?
X[:,0]

array(['Isci', 'Memur', 'Müzisyen', 'Pazarlamaci', 'Memur', 'Pazarlamaci',
       'Müzisyen', 'Doktor', 'Tuhafiyeci', 'Tornacı', 'Doktor', 'Berber',
       'Berber', 'Asistan'], dtype=object)

#  Kategorik Niteliklerin İşlenmesi

## Hedef Değişkenin LabelEncoder ile Kodlanması

In [17]:
# Bu veri setinde hedef değişken olmadığından yapılamıyor.

<img src="label_one_hot.png">

## LabelEncoder

In [16]:
from sklearn.preprocessing import LabelEncoder

## meslek kategorik değişkeni

In [17]:
encoder_meslek = LabelEncoder()

In [18]:
X[:,0] = encoder_meslek.fit_transform(X[:,0])

In [19]:
X[:10]

array([[3, 'Ankara', 35.0, 3500.0],
       [4, 'Kayseri', 42.0, 4200.0],
       [5, 'Istanbul', 30.0, 9000.0],
       [6, 'Ankara', 29.0, 4200.0],
       [4, 'Ankara', 33.0, 4250.0],
       [6, 'Istanbul', 29.0, 7300.0],
       [5, 'Istanbul', 31.0, 12000.0],
       [2, 'Ankara', 33.0, 18000.0],
       [8, 'Ankara', 47.0, 4800.0],
       [7, 'Ankara', 43.0, 4200.0]], dtype=object)

## sehir kategorik değişkeni

In [20]:
encoder_sehir = LabelEncoder()

In [21]:
X[:,1] = encoder_sehir.fit_transform(X[:,1])

In [22]:
X[:10]

array([[3, 0, 35.0, 3500.0],
       [4, 2, 42.0, 4200.0],
       [5, 1, 30.0, 9000.0],
       [6, 0, 29.0, 4200.0],
       [4, 0, 33.0, 4250.0],
       [6, 1, 29.0, 7300.0],
       [5, 1, 31.0, 12000.0],
       [2, 0, 33.0, 18000.0],
       [8, 0, 47.0, 4800.0],
       [7, 0, 43.0, 4200.0]], dtype=object)

## OneHotEncoder

In [23]:
X.shape

(14, 4)

In [24]:
X[:10,:]

array([[3, 0, 35.0, 3500.0],
       [4, 2, 42.0, 4200.0],
       [5, 1, 30.0, 9000.0],
       [6, 0, 29.0, 4200.0],
       [4, 0, 33.0, 4250.0],
       [6, 1, 29.0, 7300.0],
       [5, 1, 31.0, 12000.0],
       [2, 0, 33.0, 18000.0],
       [8, 0, 47.0, 4800.0],
       [7, 0, 43.0, 4200.0]], dtype=object)

In [27]:
# 0: meslek
# 1: sehir
# 2: yas
# 3: aylik_gelir

In [25]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(handle_unknown='ignore', categories='auto')

In [26]:
# Birden sütunu ilgilendiren dönüşümleri kolay yapabilmek için kullanışlı bir sınıf (Estimator kökenli)
# Biz burada sadece OneHotEncoder için kullanacağız.
from sklearn.compose import ColumnTransformer

In [27]:
# one_hot_encode_with_ct bizim kendi verdiğiiz isimdir. onehotencoder'ı yukarıda yarattık. [0,1] ise dönüşecek
# niteliklerin indeks değerleridir.
ct = ColumnTransformer(
    [('one_hot_encode_with_ct', onehotencoder, [0,1]),], 
    remainder='passthrough'
)

In [28]:
# ColumnTransformer nesnesi ile onehotencoder nesnesini eğitip gerekli dönüşümleri gerçekleştirip X'e tekrar atayalım.
# Burada X'in boyutu(shape) değişecektir.
X = ct.fit_transform(X)

In [29]:
X.shape

(14, 15)

In [30]:
type(X)

scipy.sparse.csr.csr_matrix

In [31]:
# Burada array'e çevirmemizin sebebi bazı durumlarda  OneHotEncoder sonunda scipy.sparse.csr.csr_matrix üretilir.
X.toarray()[:3]

array([[0.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 0.0e+00,
        0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 3.5e+01,
        3.5e+03],
       [0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00,
        0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 4.2e+01,
        4.2e+03],
       [0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00,
        0.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 3.0e+01,
        9.0e+03]])

In [32]:
# Boyut hesabı:
len(df.meslek.unique())

9

In [33]:
len(df.sehir.unique())

4

In [34]:
# mevcut boyut(4) + meslek(9) + sehir(4) = 17

In [35]:
# 3 Peki niçin 15 sütun var?

In [36]:
# meslek ve sehir'in labelEncoder ile dönüşmüş orijinal nitelikleri 
# artık gereksiz olduğu için düşürüldü bu yüzden 17 değil 15 sütun var.

# Normalizasyon, Standardizasyon (StandartdScaler)

In [37]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [38]:
std_scaler = StandardScaler()

In [40]:
X_std = std_scaler.fit_transform(X.toarray())

In [41]:
X_std[:4,:]

array([[-0.2773501 , -0.40824829, -0.40824829,  3.60555128, -0.40824829,
        -0.40824829, -0.40824829, -0.2773501 , -0.2773501 ,  0.8660254 ,
        -0.52223297, -0.2773501 , -0.40824829, -0.13626313, -0.97057644],
       [-0.2773501 , -0.40824829, -0.40824829, -0.2773501 ,  2.44948974,
        -0.40824829, -0.40824829, -0.2773501 , -0.2773501 , -1.15470054,
        -0.52223297,  3.60555128, -0.40824829,  0.81757875, -0.80784506],
       [-0.2773501 , -0.40824829, -0.40824829, -0.2773501 , -0.40824829,
         2.44948974, -0.40824829, -0.2773501 , -0.2773501 , -1.15470054,
         1.91485422, -0.2773501 , -0.40824829, -0.81757875,  0.30802725],
       [-0.2773501 , -0.40824829, -0.40824829, -0.2773501 , -0.40824829,
        -0.40824829,  2.44948974, -0.2773501 , -0.2773501 ,  0.8660254 ,
        -0.52223297, -0.2773501 , -0.40824829, -0.95384188, -0.80784506]])

In [42]:
mmax_scaler = MinMaxScaler()

In [43]:
X_mmax = mmax_scaler.fit_transform(X.toarray())

In [44]:
X_mmax[:10]

array([[0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.5       , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.        , 0.        , 0.79166667, 0.04827586],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 0.29166667, 0.37931034],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.25      , 0.04827586],
       [0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 

# Kategorik değişken işleme farklı bir yöntem

In [45]:
# kategorik değişken isimlerini prefix yaparak ve pandas dataframe'i terketmeyerek kategorik
df_dummy = pd.get_dummies(df.drop('isim', axis=1), prefix=['meslek', 'sehir'], drop_first=False)

In [46]:
df_dummy.head()

sirano   yas  aylik_gelir  aylik_gelir2  yas2  aylik_gelir3  \
0       1  35.0       3500.0        3500.0  35.0        3500.0   
1       2  42.0       4200.0        4200.0  42.0        4200.0   
2       3  30.0       9000.0        9000.0  30.0        9000.0   
3       4  29.0       4200.0        4200.0  29.0        4200.0   
4       6  33.0       4250.0        4250.0  33.0        4250.0   

   meslek_Asistan  meslek_Berber  meslek_Doktor  meslek_Isci  meslek_Memur  \
0               0              0              0            1             0   
1               0              0              0            0             1   
2               0              0              0            0             0   
3               0              0              0            0             0   
4               0              0              0            0             1   

   meslek_Müzisyen  meslek_Pazarlamaci  meslek_Tornacı  meslek_Tuhafiyeci  \
0                0                   0               0                  0   
1                0                   0               0                  0   
2                1                   0               0                  0   
3                0                   1               0                  0   
4                0                   0               0                  0   

   sehir_Ankara  sehir_Istanbul  sehir_Kayseri  sehir_İzmir  
0             1               0              0            0  
1             0               0              1            0  
2             0               1              0            0  
3             1               0              0            0  
4             1               0              0            0

In [47]:
df_dummy = pd.get_dummies(df.drop('isim', axis=1), prefix=['meslek', 'sehir'], drop_first=True)

In [48]:
df_dummy.head()

sirano   yas  aylik_gelir  aylik_gelir2  yas2  aylik_gelir3  meslek_Berber  \
0       1  35.0       3500.0        3500.0  35.0        3500.0              0   
1       2  42.0       4200.0        4200.0  42.0        4200.0              0   
2       3  30.0       9000.0        9000.0  30.0        9000.0              0   
3       4  29.0       4200.0        4200.0  29.0        4200.0              0   
4       6  33.0       4250.0        4250.0  33.0        4250.0              0   

   meslek_Doktor  meslek_Isci  meslek_Memur  meslek_Müzisyen  \
0              0            1             0                0   
1              0            0             1                0   
2              0            0             0                1   
3              0            0             0                0   
4              0            0             1                0   

   meslek_Pazarlamaci  meslek_Tornacı  meslek_Tuhafiyeci  sehir_Istanbul  \
0                   0               0                  0               0   
1                   0               0                  0               0   
2                   0               0                  0               1   
3                   1               0                  0               0   
4                   0               0                  0               0   

   sehir_Kayseri  sehir_İzmir  
0              0            0  
1              1            0  
2              0            0  
3              0            0  
4              0            0

# Ödev-20

In [1]:
# ../preprocessing/healthcare_insurance_to_preprocessed.csv 
# veri setini veri ön hazırlığını yapınız.