In [7]:
import pandas as pd

In [42]:
df = pd.read_csv("D:/Datasets/adult_temiz.csv")
df.head()

age         workclass  fnlwgt  education  education_num  \
0  39.0         State-gov   77516  Bachelors             13   
1  50.0  Self-emp-not-inc   83311  Bachelors             13   
2  38.0           Private  215646    HS-grad              9   
3  53.0           Private  234721       11th              7   
4  28.0           Private  338409  Bachelors             13   

       marital_status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capital_gain  capital_loss  hours_per_week native_country output  \
0          2174             0              40  United-States  <=50K   
1             0             0              13  United-States  <=50K   
2             0             0              40  United-States  <=50K   
3             0             0              40  United-States  <=50K   
4             0             0              40           Cuba  <=50K   

   education2  
0   Bachelors  
1   Bachelors  
2     College  
3  Highschool  
4   Bachelors

# 1. Numerik Değerlerdeki Boşlukları Doldurma (SimpleImputer)

In [43]:
# Veride şuan boş nümerik nitelik yok ancak gösterim amaçlı buraya koyduk

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 16 columns):
age               32546 non-null float64
workclass         32561 non-null object
fnlwgt            32561 non-null int64
education         32561 non-null object
education_num     32561 non-null int64
marital_status    32561 non-null object
occupation        32561 non-null object
relationship      32561 non-null object
race              32561 non-null object
sex               32561 non-null object
capital_gain      32561 non-null int64
capital_loss      32561 non-null int64
hours_per_week    32561 non-null int64
native_country    32561 non-null object
output            32561 non-null object
education2        32561 non-null object
dtypes: float64(1), int64(5), object(10)
memory usage: 4.0+ MB


In [45]:
from sklearn.impute import SimpleImputer

In [46]:
imputer = SimpleImputer()

In [51]:
df['age'] = imputer.fit_transform(df['age'].values.reshape(-1,1))

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 16 columns):
age               32561 non-null float64
workclass         32561 non-null object
fnlwgt            32561 non-null int64
education         32561 non-null object
education_num     32561 non-null int64
marital_status    32561 non-null object
occupation        32561 non-null object
relationship      32561 non-null object
race              32561 non-null object
sex               32561 non-null object
capital_gain      32561 non-null int64
capital_loss      32561 non-null int64
hours_per_week    32561 non-null int64
native_country    32561 non-null object
output            32561 non-null object
education2        32561 non-null object
dtypes: float64(1), int64(5), object(10)
memory usage: 4.0+ MB


In [47]:
import numpy as np
arr = np.array([[1],[2],[3],[5]])
arr

array([[1],
       [2],
       [3],
       [5]])

In [48]:
arr2= arr.reshape(1,-1)
arr2

array([[1, 2, 3, 5]])

In [49]:
arr2.reshape(-1,1)

array([[1],
       [2],
       [3],
       [5]])

In [50]:
type(df['age'].values)

numpy.ndarray

# 2. Kategorik Niteliklerin İşlenmesi

## 2.1. Hedef Değişkenin LabelEncoder ile Kodlanması

In [84]:
from sklearn.preprocessing import LabelEncoder

In [85]:
encoder_output = LabelEncoder()

In [86]:
df['label'] = encoder_output.fit_transform(df['output'].values.reshape(-1,1))

c:\python\python36\lib\site-packages\sklearn\preprocessing\label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [87]:
df[['output','label']].head()

output  label
0  <=50K      0
1  <=50K      0
2  <=50K      0
3  <=50K      0
4  <=50K      0

## 2.2. LabelEncoder

In [55]:
from sklearn.preprocessing import LabelEncoder

In [56]:
encoder_workclass = LabelEncoder()

In [57]:
df['workclass2'] = encoder_workclass.fit_transform(df['workclass'])

In [63]:
df[ ['workclass','workclass2'] ].head()

workclass  workclass2
0         State-gov           6
1  Self-emp-not-inc           5
2           Private           3
3           Private           3
4           Private           3

## 2.3. OneHotEncoder

In [64]:
from sklearn.preprocessing import OneHotEncoder

In [65]:
encoder = OneHotEncoder()

In [68]:
df_one_hot = encoder.fit_transform(df['workclass2'].values.reshape(-1,1))

c:\python\python36\lib\site-packages\sklearn\preprocessing\_encoders.py:414: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [73]:
len(df.workclass2.unique())

9

In [74]:
df[ ['workclass','workclass2'] ].head(10)

workclass  workclass2
0         State-gov           6
1  Self-emp-not-inc           5
2           Private           3
3           Private           3
4           Private           3
5           Private           3
6           Private           3
7  Self-emp-not-inc           5
8           Private           3
9           Private           3

In [71]:
df_one_hot.toarray()[:10]

array([[0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.]])

# 3. Normalizasyon, Standardizasyon (StandartdScaler)

In [76]:
from sklearn.preprocessing import StandardScaler

In [77]:
scaler = StandardScaler()

In [78]:
df['age3'] = scaler.fit_transform(df['age'].values.reshape(-1,1))

In [79]:
df[['age','age3']].head(10)

age      age3
0  39.0  0.030895
1  50.0  0.837539
2  38.0 -0.042436
3  53.0  1.057533
4  28.0 -0.775749
5  37.0 -0.115767
6  49.0  0.764208
7  52.0  0.984202
8  31.0 -0.555755
9  42.0  0.250889

In [80]:
from sklearn.preprocessing import MinMaxScaler

In [81]:
minmax_scaler = MinMaxScaler()

In [82]:
df['age4'] = minmax_scaler.fit_transform(df['age'].values.reshape(-1,1))

In [83]:
df[['age','age3','age4']].head(10)

age      age3      age4
0  39.0  0.030895  0.301370
1  50.0  0.837539  0.452055
2  38.0 -0.042436  0.287671
3  53.0  1.057533  0.493151
4  28.0 -0.775749  0.150685
5  37.0 -0.115767  0.273973
6  49.0  0.764208  0.438356
7  52.0  0.984202  0.479452
8  31.0 -0.555755  0.191781
9  42.0  0.250889  0.342466