In [1]:
# http://www.numpy.org/
# NumPy, Python ile vektör, matris operasyonları için temel pakettir. Ayrıca:

# güçlü bir N boyutlu dizi nesnesi
# karmaşık (yayın) fonksiyonlar
# C / C ++ ve Fortran kodunu entegre etmek için araçlar
# kullanışlı lineer cebir, Fourier dönüşümü ve rasgele sayı yetenekleri

# Belirgin bilimsel kullanımlarının yanı sıra, NumPy de çok boyutlu bir verimli veri kabı (container) olarak kullanılabilir. 
# İhtiyaca uygun veri tipleri tanımlanabilir. Bu, NumPy'nin çok çeşitli veritabanlarıyla sorunsuz ve hızlı bir şekilde bütünleşmesini sağlar.

# NumPy, BSD lisansı altında lisanslıdır. BSD lisansı Numpy'ın birkaç kısıtlama ile yeniden kullanılmasını sağlar.

In [ ]:
# NumPy'ın ana amacı, homojen çok boyutlu dizidir. 
# Bir pozitif tamsayı dizisi ile indekslenen, aynı tipte bir elementler tablosu (genellikle sayılar). 
# NumPy'de boyutlara eksen denir.

In [1]:
import numpy as np

# Tek boyutlu numpy array

In [2]:
a = np.array([1, 2, 3])

In [3]:
print(a)

[1 2 3]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print(a.shape)

(3,)


# Elemanlara Erişim

In [6]:
print(a[0])

1


In [7]:
print(a[1])

2


In [8]:
print(a[-1])

3


# Sıfırlardan oluşan tek boyutlu numpy array

In [9]:
one_dim_zeros = np.zeros(5)

In [10]:
print(one_dim_zeros)

[0. 0. 0. 0. 0.]


#  arange() - Bir sayı aralığından tek boyutlu numpy array oluşturma

In [11]:
one_dim_range = np.arange(0,10)
print(one_dim_range)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
# 0 ile 1 arasında 0.1 adımlarla 
one_dim_float = np.arange(0,1,0.1)
print(one_dim_float)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


# linspace() - Bir sayı aralığında istenen miktarda sayı üreterek tek boyutlu numpy array oluşturma

In [13]:
# 0-10 arasında eşit aralıklarla 8 sayı
one_dim_custom_range = np.linspace(0,20,8)
print(one_dim_custom_range)

[ 0.          2.85714286  5.71428571  8.57142857 11.42857143 14.28571429
 17.14285714 20.        ]


# reshape() ile Tek Boyut -> İki Boyut

In [14]:
# reshape() ile tek boyutlu array'i iki boyuta çevirebiliriz.

In [14]:
simple_array = np.array( [[1,2,3]] )

In [15]:
simple_array

array([[1, 2, 3]])

In [16]:
simple_array.shape

(1, 3)

In [17]:
simple_array.reshape(-1,1)

array([[1],
       [2],
       [3]])

In [18]:
simple_array

array([[1, 2, 3]])

In [19]:
simple_array.shape

(1, 3)

In [36]:
x = simple_array.reshape(-1,1)

In [37]:
x.shape

(3, 1)

In [38]:
simple_array.reshape(1,-1)

array([[1, 2, 3]])

In [39]:
simple_array

array([[1, 2, 3]])

# İki boyutlu numpy array

In [20]:
# liste içinde iki liste ile
two_dim = np.array([[1,2,3],[4,5,6]])

In [21]:
print(two_dim)

[[1 2 3]
 [4 5 6]]


In [22]:
print(type(two_dim))

<class 'numpy.ndarray'>


In [23]:
print(two_dim.shape)

(2, 3)


# matrisin devriği transpoze - T

In [44]:
# sütunlar satır, satırlar sütun

In [24]:
two_dim_transpoze = two_dim.T
print(two_dim_transpoze)

[[1 4]
 [2 5]
 [3 6]]


# Sıfırlardan Oluşan İki Boyutlu numpy array 

In [25]:
# ilk değer satır satısı ikinci değer sütun sayısı
two_dim_zeros = np.zeros([3,4])

In [26]:
print(two_dim_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Birlerden Oluşan İki Boyutlu numpy array

In [27]:
two_dim_ones = np.ones([5,2])

In [28]:
print(two_dim_ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


# random.random() - Rastgele ondalıklı sayılardan oluşan iki boyutlu numpy array

In [29]:
two_dim_rand = np.random.random((3,7))

In [30]:
print(two_dim_rand)

[[0.45405568 0.55065257 0.11944405 0.75524919 0.98413636 0.50438089
  0.65660008]
 [0.44546209 0.38837144 0.6911299  0.63094886 0.42900576 0.66976581
  0.44828501]
 [0.22113761 0.32573144 0.18171731 0.12018165 0.7038363  0.89000305
  0.06150646]]


# eye() - Birim Matris Oluşturma 

In [31]:
birim_matris = np.eye(5)
print(birim_matris)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Matris içindeki en büyük sayı

In [32]:
print(two_dim_rand.max())

0.9841363562565615


# Maksimum değerin yeri

In [33]:
print(two_dim_rand.argmax())

4


# Boyut

In [34]:
# Array kaç boyutlu?
print(two_dim_rand.ndim)

2


In [35]:
# Boyutların ölçüleri nedir?
print(two_dim_rand.shape)

(3, 7)
