In [1]:
import numpy as np

In [2]:
two_dim_float = np.random.rand(5,5)
print(two_dim_float)

[[0.59876176 0.62015102 0.49435859 0.76329647 0.52300701]
 [0.05083535 0.65089501 0.02347592 0.57584922 0.37151169]
 [0.68703714 0.30741033 0.61871409 0.23863769 0.79587465]
 [0.1928868  0.54542898 0.85358245 0.72512937 0.31098882]
 [0.55140347 0.2254639  0.62160593 0.84203173 0.08957989]]


# Sonuçların her defasında aynı olması için seed()

In [3]:
np.random.seed(142)
two_dim_float = np.random.rand(20,5)
print(two_dim_float)

[[0.90206152 0.55780754 0.65598471 0.83247141 0.19988419]
 [0.12725426 0.77143911 0.43228855 0.38528223 0.78364337]
 [0.78553162 0.16280861 0.11511333 0.33252155 0.60157345]
 [0.87780234 0.61487722 0.4240039  0.95784627 0.85408447]
 [0.77414528 0.87562841 0.07835524 0.03195872 0.70624246]
 [0.55297016 0.85526749 0.95410747 0.47497613 0.5481674 ]
 [0.73452535 0.53863186 0.74511416 0.57850545 0.17615075]
 [0.7574693  0.94823633 0.87774122 0.85551533 0.30142755]
 [0.10967141 0.90606606 0.91997995 0.41728586 0.02939565]
 [0.00279215 0.03273918 0.11586205 0.84782962 0.38098088]
 [0.50243638 0.46144977 0.33269178 0.42668256 0.05478812]
 [0.99436716 0.3954295  0.23951437 0.53775309 0.88952722]
 [0.57287549 0.25017651 0.3854606  0.77271445 0.35044493]
 [0.44390929 0.41410322 0.5387974  0.91819081 0.26326296]
 [0.77809458 0.59960131 0.23799241 0.53823699 0.35778167]
 [0.41327015 0.50535019 0.03588528 0.30383571 0.87276851]
 [0.99041613 0.43951434 0.81490461 0.28016241 0.07019716]
 [0.92639589 0

# Numpy çok boyutlu ndarray kesit alma

In [4]:
print(two_dim_float[:])

[[0.90206152 0.55780754 0.65598471 0.83247141 0.19988419]
 [0.12725426 0.77143911 0.43228855 0.38528223 0.78364337]
 [0.78553162 0.16280861 0.11511333 0.33252155 0.60157345]
 [0.87780234 0.61487722 0.4240039  0.95784627 0.85408447]
 [0.77414528 0.87562841 0.07835524 0.03195872 0.70624246]
 [0.55297016 0.85526749 0.95410747 0.47497613 0.5481674 ]
 [0.73452535 0.53863186 0.74511416 0.57850545 0.17615075]
 [0.7574693  0.94823633 0.87774122 0.85551533 0.30142755]
 [0.10967141 0.90606606 0.91997995 0.41728586 0.02939565]
 [0.00279215 0.03273918 0.11586205 0.84782962 0.38098088]
 [0.50243638 0.46144977 0.33269178 0.42668256 0.05478812]
 [0.99436716 0.3954295  0.23951437 0.53775309 0.88952722]
 [0.57287549 0.25017651 0.3854606  0.77271445 0.35044493]
 [0.44390929 0.41410322 0.5387974  0.91819081 0.26326296]
 [0.77809458 0.59960131 0.23799241 0.53823699 0.35778167]
 [0.41327015 0.50535019 0.03588528 0.30383571 0.87276851]
 [0.99041613 0.43951434 0.81490461 0.28016241 0.07019716]
 [0.92639589 0

In [5]:
# ilk iki sütun (0,1 indeks) tüm satırlar
print(two_dim_float[:,0:2])

[[0.90206152 0.55780754]
 [0.12725426 0.77143911]
 [0.78553162 0.16280861]
 [0.87780234 0.61487722]
 [0.77414528 0.87562841]
 [0.55297016 0.85526749]
 [0.73452535 0.53863186]
 [0.7574693  0.94823633]
 [0.10967141 0.90606606]
 [0.00279215 0.03273918]
 [0.50243638 0.46144977]
 [0.99436716 0.3954295 ]
 [0.57287549 0.25017651]
 [0.44390929 0.41410322]
 [0.77809458 0.59960131]
 [0.41327015 0.50535019]
 [0.99041613 0.43951434]
 [0.92639589 0.68892371]
 [0.13747977 0.89235468]
 [0.3933076  0.45127255]]


In [6]:
# tüm sütunlar (5-15) arası satırlar
two_dim_float[5:15,:]

array([[0.55297016, 0.85526749, 0.95410747, 0.47497613, 0.5481674 ],
       [0.73452535, 0.53863186, 0.74511416, 0.57850545, 0.17615075],
       [0.7574693 , 0.94823633, 0.87774122, 0.85551533, 0.30142755],
       [0.10967141, 0.90606606, 0.91997995, 0.41728586, 0.02939565],
       [0.00279215, 0.03273918, 0.11586205, 0.84782962, 0.38098088],
       [0.50243638, 0.46144977, 0.33269178, 0.42668256, 0.05478812],
       [0.99436716, 0.3954295 , 0.23951437, 0.53775309, 0.88952722],
       [0.57287549, 0.25017651, 0.3854606 , 0.77271445, 0.35044493],
       [0.44390929, 0.41410322, 0.5387974 , 0.91819081, 0.26326296],
       [0.77809458, 0.59960131, 0.23799241, 0.53823699, 0.35778167]])

In [7]:
# 2. satırın tüm sütunları

In [8]:
two_dim_float[2,:]

array([0.78553162, 0.16280861, 0.11511333, 0.33252155, 0.60157345])

# Matris elemanlarına erişim ve değer değiştirme

In [9]:
# 5. satırın ilk elemanı (0. indis)
two_dim_float[5][0]

0.5529701563482825

In [10]:
two_dim_float[5][0] = 0.7777701563482825

In [11]:
two_dim_float[5][0]

0.7777701563482825

# Filtreleme

In [21]:
# Oluştururken veri türünü float yapabiliriz.
two_two = np.array([[1,2,3,4,5],[6,7,8,9,10]], dtype=float)

In [22]:
print(two_two)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [23]:
two_two[two_two > 5]

array([ 6.,  7.,  8.,  9., 10.])

In [24]:
ikiden_buyuk_filtre = two_two >2
print(ikiden_buyuk_filtre)

[[False False  True  True  True]
 [ True  True  True  True  True]]


In [25]:
two_two < 5

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False]])

In [26]:
two_two[two_two >2]

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
two_two[two_two < 5]

array([1., 2., 3., 4.])

# reshape() Şekil değiştirme

In [28]:
y = np.random.random(16)
print(y)

[0.23157629 0.61623632 0.0340772  0.10783419 0.50222302 0.54236572
 0.01317082 0.04669455 0.82161584 0.71391049 0.57202814 0.38256664
 0.53612128 0.24153774 0.53883707 0.30521564]


In [29]:
y.shape

(16,)

In [30]:
y = y.reshape(-1,1)
y

array([[0.23157629],
       [0.61623632],
       [0.0340772 ],
       [0.10783419],
       [0.50222302],
       [0.54236572],
       [0.01317082],
       [0.04669455],
       [0.82161584],
       [0.71391049],
       [0.57202814],
       [0.38256664],
       [0.53612128],
       [0.24153774],
       [0.53883707],
       [0.30521564]])

In [31]:
y.shape

(16, 1)

# ravel() şekli bozmak

In [32]:
y = y.ravel()
y

array([0.23157629, 0.61623632, 0.0340772 , 0.10783419, 0.50222302,
       0.54236572, 0.01317082, 0.04669455, 0.82161584, 0.71391049,
       0.57202814, 0.38256664, 0.53612128, 0.24153774, 0.53883707,
       0.30521564])

In [33]:
y.shape

(16,)

# Horizantal stack hstack() ile array birleştirme

In [34]:
a1 = np.array([11,12,13])
a2 = np.array([21,22,23])

In [35]:
hs_a1a2 = np.hstack([a1,a2])
print(hs_a1a2)

[11 12 13 21 22 23]


# Vertical stack vstack() ile array birleştirme

In [36]:
vs_a1a2 = np.vstack([a1,a2])
print(vs_a1a2)

[[11 12 13]
 [21 22 23]]
