In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.14.0'

## 1. Tensor
n-dim array

In [3]:
hello = tf.constant("Hello ")

In [4]:
world = tf.constant("World")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [7]:
# şayet içeriği yazdırmak istiyorsak bunu bir Graph üzerinde ve session içinde çalıştırmalıyız.

In [8]:
# with ile çalışmamızın sebebi session açar blok içini çalıştırır ve session kapatır

with tf.Session() as sess:
    result = sess.run(hello+world)

In [9]:
print(result)

b'Hello World'


In [10]:
# b nedir? bytes literal boş verin

In [11]:
a = tf.constant(10)
b = tf.constant(20)
a + b 

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [13]:
with tf.Session() as sess:
    result = sess.run(a + b)

In [14]:
print(result)

30


In [15]:
const = tf.constant(10)

In [16]:
fill_mat = tf.fill((4,4), 10)

In [17]:
my_zeros = tf.zeros((4,4))

In [18]:
my_ones = tf.ones((4,4))

In [21]:
# normal dağılım
my_randn = tf.random_normal((4,4), mean=0.0, stddev=1.0)

In [22]:
# uniform dağılım
my_randu = tf.random_uniform((4,4), minval=0, maxval=1)

In [23]:
my_ops = [const, fill_mat, my_zeros, my_ones, my_randn, my_randu]

## Interactive Session for Jupyter

In [24]:
# Bu parağraftan sonrakiler sess ile çalışacaktır.
sess = tf.InteractiveSession()

In [28]:
for op in my_ops:
    print(op)
    print(sess.run(op))
    print("\n")

Tensor("Const_4:0", shape=(), dtype=int32)
10


Tensor("Fill:0", shape=(4, 4), dtype=int32)
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


Tensor("zeros:0", shape=(4, 4), dtype=float32)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Tensor("ones:0", shape=(4, 4), dtype=float32)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Tensor("random_normal:0", shape=(4, 4), dtype=float32)
[[-0.1911721  -0.41469732 -0.12573224 -0.2113553 ]
 [ 0.69993323  0.8194487   1.199255   -2.3190935 ]
 [ 0.09381751  0.5526061   0.3465087  -0.05082769]
 [ 0.63065654  0.21669443 -0.7459664  -0.1268345 ]]


Tensor("random_uniform:0", shape=(4, 4), dtype=float32)
[[0.61267316 0.76108813 0.20776784 0.13245177]
 [0.34752822 0.34896493 0.6148461  0.40823567]
 [0.04842293 0.8049512  0.01549411 0.18632519]
 [0.9377184  0.84755147 0.73708963 0.28256118]]




In [ ]:
#Ancak with tf.Session() as sess:
# kullanımı yaygındır. Sık sık bu şekilde karşımıza çıkar. 
# import pandas as pd gibi

## Matrix Multipication with Tensorflow

In [29]:
a = tf.constant([ [1,2],
                  [3,4]  ])

In [30]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [31]:
b = tf.constant([ [10], [100] ])

In [33]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [34]:
# boyutların uygun olmasına dikkat. 
# Birincinin sütun sayısı ikincinin satır sayısına eşit olmalı.
result = tf.matmul(a,b)

In [36]:
sess.run(result)

array([[210],
       [430]])