In [1]:
import tensorflow as tf
import numpy as np

In [2]:
np.random.seed(101)
tf.set_random_seed(101)

In [3]:
tf.__version__

'1.14.0'

![image.png](simple_ann_schema.png)
Görsel: https://www.udemy.com/complete-guide-to-tensorflow-for-deep-learning-with-python

## Jupyter'e özgü interaktif session

In [4]:
sess = tf.InteractiveSession()

## Boyutlar

In [5]:
n_features = 10
n_dense_neurons = 3

## input olarak x

In [6]:
# x'lerimiz ne olacak bilmiyoruz o yüzden yer tutucu kullanıyoruz.
# shape kısmında satır sayısına None dedik çünkü batch size şuan bilmiyoruz
# Batch size ağı besleme esnasındaki bir arada girilen staır sayısı
x = tf.placeholder(tf.float32, (None, n_features))

## Ağırlık/katsayı/weight olarak W

In [7]:
# Ağırlığımız yani x'lerin katsayıları. Genelde başlangış değeri olarak 0-1
# arası bir değer verilir.
W = tf.Variable(tf.random_normal( [n_features, n_dense_neurons] ))

In [8]:
sess.run(tf.random_normal( [n_features, n_dense_neurons]))

array([[-0.33280614,  1.2702985 , -0.47111124],
       [ 0.64046067,  0.22630073,  1.6514024 ],
       [-0.50997734, -0.03110447, -0.8991391 ],
       [ 0.06735504, -0.02050027,  0.9054657 ],
       [ 0.13053663, -0.6236509 ,  1.740842  ],
       [-0.12082776, -0.70383835,  1.1355529 ],
       [-0.49338904, -0.3851979 , -0.91806746],
       [ 2.0413523 ,  0.8281394 ,  0.12083016],
       [-1.0672375 , -0.08883611, -0.47264633],
       [ 0.41959324, -0.6774816 ,  1.1672206 ]], dtype=float32)

## Bias olarak b

In [9]:
# bias terimi olarak her bir neuron başına bir sabit verdik
b = tf.Variable( tf.ones([n_dense_neurons]))

In [10]:
sess.run(b.initializer)
sess.run(b)

array([1., 1., 1.], dtype=float32)

## Operasyon: Ağırlıklarla niteliklerin çarpımı xW

In [11]:
# x'in satır sayısı 10, W sütun sayısı 10 olduğuna göre matris çarpımı olabilir.
# matris çarpımında temel kural çarpılacak matris şekilleri (a,b) (b,c) olmalıdır
xW = tf.matmul(x,W)

## Operasyon: Bias ekleme

In [12]:
z = tf.add(xW, b)

## Aktivasyon Fonksiyonu

In [13]:
# a = tf.tanh
# a = tf.nn.relu
a = tf.sigmoid(z)

## Değişkenleri ilklendirme (initialize)

In [14]:
init = tf.global_variables_initializer()
sess.run(init)

## Katmanı (layer) çalıştırma ve sonuçları görme

In [15]:
layer_out = sess.run(a, feed_dict={x:np.random.random( [1, n_features] )})

In [16]:
print(layer_out)

[[0.725475   0.43900672 0.30847842]]
