In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#### veri seti bilgi: https://archive.ics.uci.edu/ml/datasets/wine
Bu veriler, İtalya'da aynı bölgede yetişen ancak üç farklı çeşitten elde edilen şarapların kimyasal analizinin sonuçlarıdır. Analiz, üç şarap türünün her birinde bulunan 13 bileşen miktarını belirledi.

In [2]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data')

In [3]:
df.head()

1  14.23  1.71  2.43  15.6  127   2.8  3.06   .28  2.29  5.64  1.04  3.92  \
0  1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
1  1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
2  1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
3  1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   
4  1  14.20  1.76  2.45  15.2  112  3.27  3.39  0.34  1.97  6.75  1.05  2.85   

   1065  
0  1050  
1  1185  
2  1480  
3   735  
4  1450

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 177 entries, 0 to 176
Data columns (total 14 columns):
1        177 non-null int64
14.23    177 non-null float64
1.71     177 non-null float64
2.43     177 non-null float64
15.6     177 non-null float64
127      177 non-null int64
2.8      177 non-null float64
3.06     177 non-null float64
.28      177 non-null float64
2.29     177 non-null float64
5.64     177 non-null float64
1.04     177 non-null float64
3.92     177 non-null float64
1065     177 non-null int64
dtypes: float64(11), int64(3)
memory usage: 19.4 KB


In [5]:
df.describe()

1       14.23        1.71        2.43        15.6         127  \
count  177.000000  177.000000  177.000000  177.000000  177.000000  177.000000   
mean     1.943503   12.993672    2.339887    2.366158   19.516949   99.587571   
std      0.773991    0.808808    1.119314    0.275080    3.336071   14.174018   
min      1.000000   11.030000    0.740000    1.360000   10.600000   70.000000   
25%      1.000000   12.360000    1.600000    2.210000   17.200000   88.000000   
50%      2.000000   13.050000    1.870000    2.360000   19.500000   98.000000   
75%      3.000000   13.670000    3.100000    2.560000   21.500000  107.000000   
max      3.000000   14.830000    5.800000    3.230000   30.000000  162.000000   

              2.8        3.06         .28        2.29        5.64        1.04  \
count  177.000000  177.000000  177.000000  177.000000  177.000000  177.000000   
mean     2.292260    2.023446    0.362316    1.586949    5.054802    0.956983   
std      0.626465    0.998658    0.124653    0.571545    2.324446    0.229135   
min      0.980000    0.340000    0.130000    0.410000    1.280000    0.480000   
25%      1.740000    1.200000    0.270000    1.250000    3.210000    0.780000   
50%      2.350000    2.130000    0.340000    1.550000    4.680000    0.960000   
75%      2.800000    2.860000    0.440000    1.950000    6.200000    1.120000   
max      3.880000    5.080000    0.660000    3.580000   13.000000    1.710000   

             3.92         1065  
count  177.000000   177.000000  
mean     2.604294   745.096045  
std      0.705103   314.884046  
min      1.270000   278.000000  
25%      1.930000   500.000000  
50%      2.780000   672.000000  
75%      3.170000   985.000000  
max      4.000000  1680.000000

## Başlık bilgisini None girelim

In [6]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data',
                header=None)

In [7]:
df.head()

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
0     178 non-null int64
1     178 non-null float64
2     178 non-null float64
3     178 non-null float64
4     178 non-null float64
5     178 non-null int64
6     178 non-null float64
7     178 non-null float64
8     178 non-null float64
9     178 non-null float64
10    178 non-null float64
11    178 non-null float64
12    178 non-null float64
13    178 non-null int64
dtypes: float64(11), int64(3)
memory usage: 19.5 KB


## Sütun isimlerini değiştirelim

In [9]:
# https://archive.ics.uci.edu/ml/datasets/wine 
# adresindeki açıklamalardan uyarlanmıştır.
cols = ['label','alcohol','malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols','flavanoids',
'nonflavanoid_phenols','proanthocyanins','color_intensity', 'hue', 'OD280-OD315_of_diluted_wines',
'proline']

In [10]:
df.columns = cols

In [11]:
df.head()

label  alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  \
0      1    14.23        1.71  2.43               15.6        127   
1      1    13.20        1.78  2.14               11.2        100   
2      1    13.16        2.36  2.67               18.6        101   
3      1    14.37        1.95  2.50               16.8        113   
4      1    13.24        2.59  2.87               21.0        118   

   total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   color_intensity   hue  OD280-OD315_of_diluted_wines  proline  
0             5.64  1.04                          3.92     1065  
1             4.38  1.05                          3.40     1050  
2             5.68  1.03                          3.17     1185  
3             7.80  0.86                          3.45     1480  
4             4.32  1.04                          2.93      735

## Sütunları tekrar sıralama hedef değişkeni sona atma

In [12]:
df = df[['alcohol','malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols','flavanoids',
'nonflavanoid_phenols','proanthocyanins','color_intensity', 'hue', 'OD280-OD315_of_diluted_wines',
'proline','label']]

In [13]:
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6        127           2.80   
1    13.20        1.78  2.14               11.2        100           2.65   
2    13.16        2.36  2.67               18.6        101           2.80   
3    14.37        1.95  2.50               16.8        113           3.85   
4    13.24        2.59  2.87               21.0        118           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280-OD315_of_diluted_wines  proline  label  
0                          3.92     1065      1  
1                          3.40     1050      1  
2                          3.17     1185      1  
3                          3.45     1480      1  
4                          2.93      735      1

## Hedef değişkene göre gözlem sayıları

In [14]:
df.groupby(['label']).alcohol.agg(['count']).head()

count
label       
1         59
2         71
3         48

## Veri Setini X ve y olarak ikiye ayırma (dikey bölme)

In [15]:
X = df.iloc[:,:-1].values
X.shape

(178, 13)

In [16]:
y = df.iloc[:,-1].values
y.shape

(178,)

## Standardizasyon (Feature Scaling)

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
scaler = StandardScaler()

In [19]:
X_scaled = scaler.fit_transform(X)

In [20]:
X_scaled[:2]

array([[ 1.51861254, -0.5622498 ,  0.23205254, -1.16959318,  1.91390522,
         0.80899739,  1.03481896, -0.65956311,  1.22488398,  0.25171685,
         0.36217728,  1.84791957,  1.01300893],
       [ 0.24628963, -0.49941338, -0.82799632, -2.49084714,  0.01814502,
         0.56864766,  0.73362894, -0.82071924, -0.54472099, -0.29332133,
         0.40605066,  1.1134493 ,  0.96524152]])

## PCA

In [21]:
from sklearn.decomposition import PCA

In [22]:
pca = PCA(n_components = None)

In [23]:
X_pca = pca.fit_transform(X_scaled)
X_pca.shape

(178, 13)

## Açıklanan Varyans (explained variance)

In [24]:
explained_variances = pca.explained_variance_ratio_
explained_variances

array([0.36198848, 0.1920749 , 0.11123631, 0.0706903 , 0.06563294,
       0.04935823, 0.04238679, 0.02680749, 0.02222153, 0.01930019,
       0.01736836, 0.01298233, 0.00795215])

In [25]:
# bunlar orjinal nitelikler değil yeni temel bileşenler
# Örneğin ilk iki bileşeni seçersek 0.36198848 + 0.1920749 = 0.553 açıklanan varyansa ulaşmış oluruz.
# yani 13 değişken yerine en temel iki temel bileşeni kullanmak varyansın yarısından fazlasını
# açıklamamızı sağlıyor.

In [26]:
# Artık n_components'i buraya bakarak karar verebiliriz.

In [27]:
pca = PCA(n_components = 2)
X_pca = pca.fit_transform(X_scaled)
X_pca.shape

(178, 2)

In [28]:
# X_pca ile artık sınıflandırma ya da kümeleme yapabiliriz.

# Veri setini train ve test olarak ayırma

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_pca, y, test_size=0.25, random_state=142)

## Sınıflandırma

In [30]:
from sklearn.linear_model import LogisticRegression

In [31]:
classifier = LogisticRegression(random_state=142)

In [32]:
classifier.fit(X_train, y_train)

c:\python\python36\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
c:\python\python36\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=142, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

## Model ile test seti üzerinde tahmin yapma

In [33]:
y_pred = classifier.predict(X_test)

## Hata Matrisi

In [34]:
from sklearn.metrics import confusion_matrix

In [35]:
cm = confusion_matrix(y_pred=y_pred, y_true=y_test)

In [36]:
cm

array([[15,  1,  0],
       [ 1, 16,  0],
       [ 0,  0, 12]], dtype=int64)

## Accuracy

In [37]:
from sklearn.metrics import accuracy_score

In [38]:
accuracy_score(y_pred=y_pred, y_true=y_test)

0.9555555555555556